### ISSUE TITLE
Out of range error

### ISSUE THREAD

**Issue by SiddhartaDutta** [SiddhartaDutta/Spotify-to-MP3#7]
Prevents image tags from being applied

**Comment by SiddhartaDutta** [comment]
Error:
```
Traceback (most recent call last):
  File "/home/siddh/Projects/Spotify-Downloader/main.py", line 57, in <module>
    osScripts.update_img_tags()
  File "/home/siddh/Projects/Spotify-Downloader/osScripts.py", line 279, in update_img_tags
    add_img_to_id3_for_album(directory)
  File "/home/siddh/Projects/Spotify-Downloader/osScripts.py", line 246, in add_img_to_id3_for_album
    albumCoverPath = glob.glob('*.jpg')[0]
IndexError: list index out of range
```
